In [1]:
import numpy as np

## Key Distributions

This section illustrates the five most important distributions in the context of discrete models (of which multinomial models are part of).

In [2]:
rng = np.random.default_rng(2025)

### Bernoulli Distribution

In [3]:
rng.binomial(n=1, p = 0.3)

1

### Binomial Distribution

In [ ]:
### Out code here
pvals = rng.binomial()

### Categorical Distribution

In [9]:
# Method one
### Our code here

rng.choice([1,2,3], p = [0.2, 0.2, 0.6], size=20)

# Method two: Special case of multinomial
### Out code here
#rng.multinomial(n=200, pvals = [0.2, 0.2, 0.6], size = 5)


array([2, 1, 2, 3, 3, 3, 2, 3, 3, 3, 1, 2, 3, 3, 3, 2, 3, 3, 3, 3])

### Multinomial Distribution

In [8]:
### Our code here

rng.multinomial(n=200, pvals = [0.2, 0.2, 0.6], size = 5)

array([[ 42,  39, 119],
       [ 31,  42, 127],
       [ 53,  43, 104],
       [ 45,  41, 114],
       [ 40,  37, 123]])

### Dirichlet Distribution

In [129]:
### Our code here
rng.dirichlet(alpha=[1, 1, 10], size=100).mean(axis=0)

array([0.08876438, 0.09050094, 0.82073468])

## Basic MPT Models

One-high-threshold (1HT) vs. two-high-threshold models (see slides)

In [ ]:
print("Hello")